build:
  test:
    image: python:3.5-alpine
    commands:
      - apk add --update bash make ca-certificates
      - pip install -r requirements-dev.txt
      - pip install coveralls
      - make test
      - coveralls

publish:
  pypi:
    repository: https://repository.prod.aws.skyscnr.com/artifactory/api/pypi/pypi
    username: $$PYPI_USERNAME
    password: $$PYPI_PASSWORD
    distributions:
      - bdist_wheel
    when:
      event: push
      branch: master
