build:
  test:
    image: python:3-alpine
    commands:
      # - apk add --update bash make ca-certificates
      # - python setup.py install
      # - make init test
      - rm -rf tests
  versioning:
    image: python:3-alpine
    commands:
      - sed -i '/__version__/c\__version__ = "$$TAG"' moto/__init__.py
    when:
      event: tag

publish:
  pypi:
    repository: https://repository.prod.aws.skyscnr.com/artifactory/api/pypi/pypi
    username: $$PYPI_USERNAME
    password: $$PYPI_PASSWORD
    distributions:
      - bdist_wheel
    when:
      event: tag
